import { game } from '../game.js';
import { exportSave, importSave, wipeSave, saveState } from '../state.js';
import { openModal, bindActions, toast, confirmDialog, infoDialog } from './ui.js';
import { sfx } from '../audio.js';

export const settingsPanel = {
  open() {
    const st = game.state;
    const isStandalone = window.navigator.standalone === true || window.matchMedia('(display-mode: standalone)').matches;
    openModal({
      title: 'Settings',
      html: `<div class="card">
          <label class="row between"><span>Sound effects</span><input type="checkbox" id="opt-sound" ${st.settings.sound ? 'checked' : ''}></label>
        </div>
        <div class="card">
          <b>Save data</b>
          <p class="hint">Your game saves automatically on this device. Export a code to move it to another phone.</p>
          <div class="row gap wrap"><button class="btn ghost" data-action="export">Export save</button><button class="btn ghost" data-action="import">Import save</button></div>
        </div>
        ${!isStandalone ? `<div class="card"><b>Play fullscreen on iPhone</b><p class="hint">Open this page in Safari, tap the <b>Share</b> button, then <b>Add to Home Screen</b>. The game then runs like an app, offline too.</p></div>` : ''}
        <div class="card"><b>About</b><p class="hint">DragonSit v1 · Raise, breed and battle dragons. All art is generated by code. Made with ♥.</p></div>
        <div class="row center"><button class="btn danger ghost" data-action="reset">Reset game</button></div>`,
      onMount: (m) => {
        m.body.querySelector('#opt-sound').addEventListener('change', (e) => {
          st.settings.sound = e.target.checked;
          sfx.setEnabled(st.settings.sound);
          game.save();
        });
        bindActions(m.body, {
          export: () => {
            game.save();
            const code = exportSave(st);
            openModal({
              title: 'Your save code',
              html: `<p class="hint">Copy this code and paste it into Import on your other device.</p><textarea class="input code" readonly>${code}</textarea><div class="row center"><button class="btn primary" data-action="copy">Copy</button></div>`,
              onMount: (mm) => bindActions(mm.body, {
                copy: async () => {
                  try {
                    await navigator.clipboard.writeText(code);
                    toast('Copied!', 'good');
                  } catch (err) {
                    mm.body.querySelector('textarea').select();
                    toast('Select the text and copy it');
                  }
                },
              }),
            });
          },
          import: () => {
            openModal({
              title: 'Import save',
              html: `<p class="hint">Paste a save code. This replaces your current game.</p><textarea class="input code" id="import-code" placeholder="Paste code here"></textarea><div class="row center"><button class="btn primary" data-action="go">Import</button></div>`,
              onMount: (mm) => bindActions(mm.body, {
                go: async () => {
                  const text = mm.body.querySelector('#import-code').value;
                  try {
                    const next = importSave(text);
                    const ok = await confirmDialog('Replace save?', 'Your current progress will be overwritten.', 'Import', true);
                    if (!ok) return;
                    saveState(next);
                    location.reload();
                  } catch (err) {
                    toast('That code is not valid', 'bad');
                  }
                },
              }),
            });
          },
          reset: async () => {
            const ok = await confirmDialog('Reset game', 'Delete ALL progress and start over?', 'Delete everything', true);
            if (!ok) return;
            const ok2 = await confirmDialog('Are you sure?', 'This really cannot be undone.', 'Yes, reset', true);
            if (!ok2) return;
            wipeSave();
            game.state = null;
            location.reload();
          },
        });
      },
    });
  },
};
